run:
  tests: false
  skip-dirs:
    - mock

linters-settings:
  lll:
    line-length: 150
  maligned:
    suggest-new: true

linters:
  enable-all: true
  fast: false

issues:
  exclude-rules:
    - path: cmd/
      linters:
        - gochecknoglobals